# Generated by Django 6.0.5 on 2026-05-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_broadcasting", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="server_response",
            field=models.TextField(blank=True, verbose_name="Ответ сервера"),
        ),
    ]
